mdapi_deploy/objects/bhanu9666__MoviesDB__c.object
<CustomObject>
    <label>Movies Database</label>
    <pluralLabel>Movies Database</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <nameField>
        <type>Text</type>
        <label>Name</label>
    </nameField>
    <fields>
        <fullName>bhanu9666__Video_ID__c</fullName>
        <label>Video ID</label>
        <type>Text</type>
        <length>50</length>
    </fields>
</CustomObject>

deploy_pkg/classes/MovieDbTriggerHandler.cls
public class MovieDbTriggerHandler {
    public static void handleTrigger(List<bhanu9666__MoviesDB__c> newRecords, Map<Id, bhanu9666__MoviesDB__c> oldMap) {
        Set<String> processed = new Set<String>();
        Set<String> videoIds = new Set<String>();
        for (bhanu9666__MoviesDB__c r : newRecords) {
            if (r.bhanu9666__Video_ID__c != null && !processed.contains(r.bhanu9666__Video_ID__c)) {
                videoIds.add(r.bhanu9666__Video_ID__c);
                processed.add(r.bhanu9666__Video_ID__c);
            }
        }
        MovieDbService svc = new MovieDbService();
        svc.processRecords(newRecords);
        if (!videoIds.isEmpty()) svc.enrichFromExternalSource(newRecords, videoIds);
    }
}