mdapi_deploy/objects/bhanu9666__MoviesDB__c.object
<CustomObject>
    <label>Movies Database</label>
    <pluralLabel>Movies Database</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <nameField>
        <type>Text</type>
        <label>Name</label>
    </nameField>
    <fields>
        <fullName>bhanu9666__Cast__c</fullName>
        <label>Cast</label>
        <type>LongTextArea</type>
        <length>32000</length>
    </fields>
    <fields>
        <fullName>bhanu9666__Cast_Count__c</fullName>
        <label>Cast Count</label>
        <type>Number</type>
        <precision>5</precision>
        <scale>0</scale>
    </fields>
    <fields>
        <fullName>bhanu9666__Duration__c</fullName>
        <label>Duration</label>
        <type>Text</type>
        <length>20</length>
    </fields>
    <fields>
        <fullName>bhanu9666__Duration_Minutes__c</fullName>
        <label>Duration Minutes</label>
        <type>Number</type>
        <precision>5</precision>
        <scale>0</scale>
    </fields>
    <fields>
        <fullName>bhanu9666__Genre_List__c</fullName>
        <label>Genre List</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>bhanu9666__Genres__c</fullName>
        <label>Genres</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Comedy</fullName>
                </value>
                <value>
                    <fullName>Drama</fullName>
                </value>
                <value>
                    <fullName>Thriller</fullName>
                </value>
                <value>
                    <fullName>Romance</fullName>
                </value>
                <value>
                    <fullName>Sci-Fi</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>bhanu9666__Is_Featured__c</fullName>
        <label>Is Featured</label>
        <type>Checkbox</type>
        <defaultValue>false</defaultValue>
    </fields>
    <fields>
        <fullName>bhanu9666__Is_Top_10__c</fullName>
        <label>Is Top 10</label>
        <type>Checkbox</type>
        <defaultValue>false</defaultValue>
    </fields>
    <fields>
        <fullName>bhanu9666__Match_Score__c</fullName>
        <label>Match Score</label>
        <type>Text</type>
        <length>20</length>
    </fields>
    <fields>
        <fullName>bhanu9666__Match_Score_Value__c</fullName>
        <label>Match Score Value</label>
        <type>Number</type>
        <precision>5</precision>
        <scale>2</scale>
    </fields>
    <fields>
        <fullName>bhanu9666__Normalized_Rating__c</fullName>
        <label>Normalized Rating</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UA</fullName>
                    <default>true</default>
                    <label>UA</label>
                </value>
                <value>
                    <fullName>U</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>Not_Rated</fullName>
                    <label>Not Rated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>bhanu9666__Rating__c</fullName>
        <label>Rating</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UA</fullName>
                    <default>true</default>
                    <label>U/A</label>
                </value>
                <value>
                    <fullName>U</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>bhanu9666__Video_ID__c</fullName>
        <label>Video ID</label>
        <type>Text</type>
        <length>50</length>
    </fields>
    <fields>
        <fullName>bhanu9666__YouTube_Embed_URL__c</fullName>
        <label>YouTube Embed URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>bhanu9666__YouTube_Thumbnail_1280__c</fullName>
        <label>YouTube Thumbnail</label>
        <type>Url</type>
    </fields>
</CustomObject>

deploy_pkg/classes/MovieDbService.cls
public class MovieDbService {
    public void processRecords(List<bhanu9666__MoviesDB__c> records) {
        for (bhanu9666__MoviesDB__c record : records) {
            if (record.bhanu9666__Match_Score__c != null) {
                record.bhanu9666__Match_Score_Value__c = parseScore(record.bhanu9666__Match_Score__c);
            }
            if (record.bhanu9666__Duration__c != null) {
                record.bhanu9666__Duration_Minutes__c = parseDuration(record.bhanu9666__Duration__c);
            }
            if (record.bhanu9666__Rating__c != null) {
                record.bhanu9666__Normalized_Rating__c = normalizeRating(record.bhanu9666__Rating__c);
            }
            if (record.bhanu9666__Genres__c != null) {
                record.bhanu9666__Genre_List__c = record.bhanu9666__Genres__c.replace(';', '|');
            }
            if (record.bhanu9666__Cast__c != null) {
                String[] parts = record.bhanu9666__Cast__c.split(',');
                record.bhanu9666__Cast_Count__c = parts.size();
            }
            if (record.bhanu9666__Video_ID__c != null) {
                record.bhanu9666__YouTube_Thumbnail_1280__c = 'https://img.youtube.com/vi/' + record.bhanu9666__Video_ID__c + '/maxresdefault.jpg';
                record.bhanu9666__YouTube_Embed_URL__c = 'https://www.youtube.com/embed/' + record.bhanu9666__Video_ID__c;
            }
            Boolean isTop10 = record.bhanu9666__Is_Top_10__c != null && record.bhanu9666__Is_Top_10__c;
            Decimal score = record.bhanu9666__Match_Score_Value__c;
            record.bhanu9666__Is_Featured__c = isTop10 || (score != null && score >= 7.0);
        }
    }
    private Decimal parseScore(String s) {
        try { return Decimal.valueOf(s.replaceAll('/.*', '').trim()); } catch(Exception e) { return null; }
    }
    private Integer parseDuration(String s) {
        Integer m = 0;
        if (s != null) {
            if (s.contains('h')) m += Integer.valueOf(s.substringBefore('h')) * 60;
            if (s.contains('m')) m += Integer.valueOf(s.substringAfter('h').substringBefore('m').replaceAll('[^0-9]', ''));
        }
        return m == 0 ? null : m;
    }
    private String normalizeRating(String r) {
        if (r == null) return null;
        String u = r.toUpperCase();
        if (u.contains('U/A') || u.contains('UA')) return 'UA';
        if (u.contains('A')) return 'A';
        if (u.contains('U')) return 'U';
        return 'Not_Rated';
    }
    public void enrichFromExternalSource(List<bhanu9666__MoviesDB__c> records, Set<String> ids) {}
}